---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product_name: chef
  product_version: 14

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[mypostgresql::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
